name: CI

on:
  push:
    branches:
      - main

jobs:
  build_test:
    name: Build, lint and test
    env:
      # The special value "local" tells Go to use the bundled Go version rather
      # than trying to fetch one according to a `toolchain` value in `go.mod`.
      # This ensures that we're really running the Go version in the CI matrix
      # rather than one that the Go command has upgraded to automatically.
      GOTOOLCHAIN: local
    strategy:
      matrix:
        go-version: [1.24]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: go test -race -count=1 ./...
